image:
- Visual Studio 2017

environment:
  MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
  TRAVIS: 1

clone_depth: 3

before_build:
- cmd: set PATH=%MINGW_DIR%;%PATH%
# fix CMake sh.exe issue, by removing Git path.
- cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
- cmd: set FC=%MINGW_DIR%\gfortran 

- sh: sudo apt -yq update > /dev/null
- sh: sudo apt install -yq --no-install-suggests --no-install-recommends gfortran-5 cmake make > /dev/null
- sh: FC=gfortran-5

- cd bin

build_script:
- cmd: cmake -G "MinGW Makefiles" ..
- cmd: mingw32-make

- sh: cmake ..
- sh: make
  
after_build:

- sh: ./nan
- sh: ./split
- sh: ./hugeprec
- sh: ./coarray/coarray_hello
- sh: ./testall

- cmd: nan
- cmd: split
- cmd: hugeprec
- cmd: testall
