language: c

sudo: true
dist: trusty

notifications:
  email: false

git:
  depth: 1
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran-5
    - libopenmpi-dev

before_install:
    - mkdir -p $HOME/.local/bin
    - ln -fs /usr/bin/gfortran-5 "$HOME/.local/bin/gfortran" 
    - gfortran --version

script: 
    - cd bin
    - FC=gfortran cmake ..
    - make VERBOSE=1

