# gfortran >= 6 is required
language: c
group: travis_latest
dist: xenial

git:
  depth: 3
  quiet: true

env: FC=gfortran

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
    - gfortran-6
    - liblapack-dev
    - libopenmpi-dev
    - openmpi-bin
    - libhdf5-dev
 #       - libnetcdf-dev
#        - libnetcdff-dev # not in image repos

matrix:
  include:
  - os: linux
    env: FC=gfortran-6
#  - os: osx
#    before_install:
  #  - brew install gcc > /dev/null
    #- brew install hdf5 netcdf > /dev/null;  # works but commented to save time
  - os: windows
    language: minimal
    install:
    - cd build
    - cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
    - cmake --build .

install:
- cd build
- cmake ..
- cmake --build .

script:
- cd $TRAVIS_BUILD_DIR/build
- ctest --output-on-failure

