language: c

os:
  - linux
  - osx

dist: trusty # not ubuntu 12.04

notifications:
  email: false

git:
  depth: 3

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['gfortran-5','libhdf5-dev','libnetcdff-dev'] #'libopenmpi-dev' wrong version mpi

before_install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
        brew update;
        brew install gcc;
        brew install hdf5;
        brew install netcdf --with-fortran;
      else
        mkdir -p $HOME/.local/bin;
        ln -fs /usr/bin/gfortran-5 "$HOME/.local/bin/gfortran";
      fi 

install:
    - gfortran --version

script: 
    - cd bin
    - cmake ..
    - make VERBOSE=1

    - ./nan
    - ./split
