# gfortran >= 6 is required
language: c
group: travis_latest
dist: xenial

git:
  depth: 3
  quiet: true


addons:
  apt:
    packages:
    - gfortran
#   - libopenmpi-dev # wrong version mpi
 #       - libhdf5-dev # old version
 #       - libnetcdf-dev
#        - libnetcdff-dev # not in image repos


matrix:
  include:
  - os: linux
    # takes 15 minutes to setup on Travis for Linux.
    #before_install:
    #- export HOMEBREW_FORCE_VENDOR_RUBY=1;
    #- sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)";
    #- export PATH="/home/travis/.linuxbrew/bin:$PATH";
    #- brew install gcc opencoarrays;
  - os: osx
    before_install:
    - brew update > /dev/null
    - brew install gcc > /dev/null
    #- brew install hdf5 netcdf > /dev/null;  # works but commented to save time



install:
- cd bin
- cmake ..
- cmake --build .

script: ctest --output-on-failure

