language: c

sudo: true
dist: trusty

notifications:
  email: false

git:
  depth: 1
  
addons:
  apt:
    packages: ['gfortran','libopenmpi-dev']

script: 
    - cd bin
    - FC=gfortran cmake ..
    - make VERBOSE=1

