# gfortran >= 6 is required
language: c
fast_finish: true

os:
  - linux
  - osx
  
env: FC=gfortran-6

group: travis_latest


git:
  depth: 3

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6
      - gcc-6
#'libopenmpi-dev' # wrong version mpi
 #       - libhdf5-dev # old version
 #       - libnetcdf-dev
#        - libnetcdff-dev # not in image repos

before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then
      brew update;
      brew install gcc || true;
      brew link --overwrite gcc;
      export FC=gfortran;
      brew install opencoarrays hdf5 netcdf open-mpi;
    fi
# takes 15 minutes to setup on Travis for Linux.    
#  - if [[ $TRAVIS_OS_NAME == linux ]]; then
#      export HOMEBREW_FORCE_VENDOR_RUBY=1;
#      sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)";
#      export PATH="/home/travis/.linuxbrew/bin:$PATH";
#      brew install gcc opencoarrays;
#    fi
    

install:
  - cd bin
  - cmake ..
  - make

script:
  - make test
    
on_failure:
  - ctest -V
