language: c

os:
  - linux
  - osx

# >= trusty required
dist: trusty

notifications:
  email: false

git:
  depth: 3

addons:
  apt:
    sources: 
        - ubuntu-toolchain-r-test
    packages: 
        - gfortran-5
#'libopenmpi-dev' # wrong version mpi
 #       - libhdf5-dev # old version
 #       - libnetcdf-dev
#        - libnetcdff-dev # not in image repos

before_install:
# mac brew has no hdf5 or netcdf
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
        brew update;
        brew install gcc;
      else
        mkdir -p $HOME/.local/bin;
        ln -fs /usr/bin/gfortran-6 "$HOME/.local/bin/gfortran";
      fi 

    - gfortran --version

install:
    - mkdir -p bin
    - cd bin
    - cmake ..
    - make

script: 
    - ./nan
    - ./split
